spring:
  application:
    name: post-handling-service

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: posts


kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8001

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#security:
#  basic:
#    enable: false
#
#  jwt:
#    uri: /auth/**
#    header: Authorization
#    prefix: Bearer
#    expiration: 86400
#    secret: JwtSecretKey