apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
data:
  neo4j.conf: |
    dbms.connector.bolt.advertised_address=neo4j:7687
    dbms.connector.http.advertised_address=neo4j:7474
    dbms.directories.data=/data
    NEO4J_AUTH=neo4j/you-scout-project

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4jdbvol-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.4.21
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        volumeMounts:
        - name: neo4jdbvol
          mountPath: /data
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: you-scout-secret
              key: neo4j-auth
      volumes:
      - name: neo4jdbvol
        persistentVolumeClaim:
          claimName: neo4jdbvol-claim

---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
  ports:
    - port: 7474
      targetPort: 7474
      name: http
    - port: 7687
      targetPort: 7687
      name: bolt