apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoia3ViZS1wdWxsZXIiLCJwYXNzd29yZCI6InAzenBzV1NaSjJuaDVSWUtWb2g5IiwiYXV0aCI6ImEzVmlaUzF3ZFd4c1pYSTZjRE42Y0hOWFUxcEtNbTVvTlZKWlMxWnZhRGs9In19fQ==
kind: Secret
metadata:
  name: registry-crds
  namespace: you-scout
type: kubernetes.io/dockerconfigjson
