default:
  tags:
    - docker

stages:
  - scan
  - version
  - build
  - deploy


variables:
  variable_value: value


versioning:
  stage: version
  script:
    - variable_value=$CI_COMMIT_REF_NAME
    - echo "Variable value $variable_value"
    - IFS='-' read -ra words <<< "$variable_value"
    - word1="${words[0]}"
    - word2=$(echo "$variable_value" | cut -d'-' -f2-)
    - echo $word1
    - echo $word2
    - variable_name="${word1}-${word2}"
    - echo "$COMMENT_VERSION"
    - |
          echo "I'm in"
          IFS='.' read -ra VERSION_ARRAY <<< "$AUTH_VERSION"
          MAJOR=${VERSION_ARRAY[0]}
          MINOR=${VERSION_ARRAY[1]}
          PATCH=${VERSION_ARRAY[2]}
          if [[ $word1 == "major" ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [[ $word1 == "minor" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [[ $word1 == "patch" ]]; then
            PATCH=$((PATCH + 1))
          fi
          echo "major $MAJOR, minor $MINOR, patch $PATCH"
          curl --request PUT --header "PRIVATE-TOKEN: glpat-rzjTbhoKA5VmBypsnB6n" "https://gitlab.com/api/v4/projects/44998572/variables/AUTH_VERSION" --form "value=$MAJOR.$MINOR.$PATCH"

auth-build:
  image: maven:3.8.4-openjdk-17
  stage: build
  before_script:
    - cd auth-service
    - export PACKAGE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/microservice/authentication
    - export VERSION=$AUTH_VERSION
  script: |
    mvn compile jib:build \
      -Djib.to.auth.username=${CI_REGISTRY_USER} \
      -Djib.to.auth.password=${CI_REGISTRY_PASSWORD} \
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    reports:
      junit:
        - "auth-service/target/*-reports/TEST-*.xml"
  cache:
    paths:
      - .m2/repository/
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_TAG == "major-auth-service" || $CI_COMMIT_TAG == "minor-auth-service" || $CI_COMMIT_TAG == "patch-auth-service"'
      changes:
      - auth-service/**/*


auth_yaml:
  image: alpine
  before_script:
    - apk add --no-cache curl
  stage: deploy
  script: |
    sed -i 's|image:.*|image: registry.gitlab.com/hamdane10/you-scout/auth-service:'$AUTH_VERSION'|' k8s/auth-service.yaml
    ENCODED_CONTENT=$(base64 -w 0 k8s/auth-service.yaml)
    curl --request PUT --header "PRIVATE-TOKEN: glpat-yw5_V7QMKPXSt52tdx5B" --header "Content-Type: application/json" --data '{"branch": "master", "author_email": "aarrasseayoub@gmail.com", "author_name": "Ayoub AARRASSE", "content": "'"$ENCODED_CONTENT"'", "commit_message": "update file", "encoding":"base64"}' "https://gitlab.com/api/v4/projects/44998572/repository/files/k8s%2Fauth-service%2Eyaml"

  rules:
    - if: '$CI_COMMIT_TAG == "major-auth-service" || $CI_COMMIT_TAG == "minor-auth-service" || $CI_COMMIT_TAG == "patch-auth-service"'
      changes:
        - auth-service/**/*
  needs:
    - job: auth-build

